const text = [
	'music to compose music to is a digital manifestation of real world environments. Music is one form of many cultural artefacts that has been copied, duplicated, and shared through multiple peer-to-peer networks in the digital age. There are more copies than there are originals on the internet. But what is an original? Who is the author? The mass circulation of information and cultural exchange, such as the virality of image files, has become central to our online worlds. Real world environments are recreated in 3D rendered video format. The spaces replicate our imagination of spaces in the real world. All material on the internet is a manifestation of our offline world. The internet has created an environment for the mass distribution of music. More music is distributed than ever before. Aesthetic experience reached a point where the image determines consumer decision making.',
	'Our experience of cultural artefacts exists via a capture of that experience in the form of documentation. Documentation exists as a digitised copy of the original work. But where does the original work end and the copy begin? What is uploaded onto the platform? Where is the music coming from? The virtual manifestation of spaces and the in real life manifestation of those spaces is said to be merging. I exist as a computer generated manifestation of a real person. Interaction with the offline world is understood more and more through the online world. Projections of our real world experience is captured and disseminated online to unknown others. Shared experiences influences engagement and behaviour IRL.',
	'The composition of the World Wide Web influenced the formalisation of music to compose music to. The internet and digital technologies are structured by categorisation. Categorisation brings inherent functionality to the form of a website. Functionality directs users to a central message. User interactivity is measured by the direct and clear message portrayed through a website. Attention is gained through a balance of familiarity and unique selling points. Creating a space on the internet is fundamental. Everything on the internet is marketable and financialised.',
	'Where are we in our virtual environment? What is the material differentiation between media formats? How are you experiencing music to compose music to? Where is my voice coming from? For how long will you stay here?',
	'Aesthetic experience is the foundation of contemporary living. The screen is a window through which we experience the world. The mediascape is flattened by the screen. All forms of media are mutable and intersect into one another. When an image is circulated it can become entirely extracted from its original context. The aesthetic spaces you are experiencing here have been manipulated to serve a particular purpose. An explanation of how the media content you are viewing has been processed and programmed is more significant than the content itself. All content on music to compose music to is extracted and reappropriated from completely unrelated contexts.',
	'Material is extracted from material and manipulated to form new material removed from its original context. What becomes of the original context? At what point is the context lost? The transformation of material is recontextualised though visual content. The transformation of that visual content is recontextualised through the screen. Extraction takes place in many forms. I am generated in written form and extracted as spoken text using a text-to-speech converter, manipulated to serve a particular context. All material objects serve the purpose of a particular goal.',
	'Where am I? Where are you? How has your experience been?',
	'The internet enabled access to infinite content. Content, such as music, videos, images, books, personal information, secrets, exists in multiple locations. The original and the copy of many files across many formats are indistinguishable on the internet. music to compose music to may become an altered version of itself. A derivative. Elements documented and distributed across various platforms. The original content featured on music to compose music to itself derives from material existing in digital and physical locations.',
]

export default text
